name: 'May Simple Workflow'
run-name: '${{ github.actor }} is testing out GitHub Actions 🚀'
on: [push]
jobs:
  Try-Github-Actions:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run frontend test
        run: |
          npm ci
          npm test